remote_theme: vaibhavvikas/jekyll-theme-minimalistic
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vaibhavvikas
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas
color-scheme: dark
layout: default
navigation:
  - name: Home
    link: /README.html
  - name: File Format
    link: /root/file_format.html
